<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutDir>bin</OutDir>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alethic.NodeApi" Version="$(NodeApiDotnetPackageVersion)" />
    <PackageReference Include="Alethic.NodeApi.Generator" Version="$(NodeApiDotnetPackageVersion)" />
  </ItemGroup>

</Project>
